.TH GAT 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH GAT
gat \- gnome front-end to at and cron
.SH SYNOPSIS
.B gat
.I "[--help] [--version]"
.br
.SH "DESCRIPTION"
.BR gat
is a gnome front-end to at and cron. It provides a simple way to schedule
one-time and recurring tasks. 
.BR gat
require no knowledge of either at or cron.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
There are two main command line options.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
.SH AUTHOR
This manual page was written by Justin Penney <jpenney@atipa.com>,
for the Debian GNU/Linux system (but may be used by others).
.BR gat
is written by Patrick Reynolds <reynolds@cs.duke.edu>.
